services:
  dev_software_com:
    image: codexion-cloud:v2
    container_name: dev_software_com
    ports:
      - "8001:8000"
      - "4001:4001"
      - "3001:3001"
    volumes:
      - ./public/dev_software_com:/home/devops/shared
    networks:
      - codexion-network
    restart: unless-stopped
    tty: true

networks:
  codexion-network:
    external: true